CREATE TABLE KURSI (
ID SERIAL PRIMARY KEY,
EMRI_KURSIT VARCHAR(100),
KOHEZGJATJA VARCHAR(100),
CREATION_DATE DATE,
UPDATE_DATE DATE);

INSERT INTO KURSI (EMRI_KURSIT, KOHEZGJATJA, CREATION_DATE, UPDATE_DATE) VALUES
('ITALISHT', '6 MUAJ', '2024-02-01', '2025-02-01'),
('GJERMANISHT', '6MUAJ', '2025-05-01', '2025-06-01'),
('ANGLISHT', '3 MUAJ', '2024-03-01', '2024-06-01'),
('FRENGJISHT', '4 MUAJ', '2024-04-10', '2024-08-10'),
('SPANJISHT', '5 MUAJ', '2024-05-15', '2024-10-15'),
('TURQISHT', '3 MUAJ', '2024-06-01', '2024-09-01'),
('ARABISHT', '6 MUAJ', '2024-07-01', '2025-01-01'),
('RUSISHT', '4 MUAJ', '2024-08-05', '2024-12-05'),
('SHQIP', '6 MUAJ', '2024-09-01', '2025-03-01'),
('JAPONISHT', '5 MUAJ', '2024-10-01', '2025-03-01');

SELECT * FROM KURSI;

ALTER TABLE KURSI ADD PROGRAMMING_LANGUAGE VARCHAR(100);

UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'JAVA' WHERE ID = 1;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'PYTHON' WHERE ID = 2;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'C++' WHERE ID = 3;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'JAVASCRIPT' WHERE ID = 4;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'C#' WHERE ID = 5;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'PHP' WHERE ID = 6;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'RUBY' WHERE ID = 7;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'GO' WHERE ID = 8;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'SWIFT' WHERE ID = 9;
UPDATE KURSI SET PROGRAMMING_LANGUAGE = 'KOTLIN' WHERE ID = 10;

DELETE FROM KURSI WHERE ID = 3;

CREATE TABLE STUDENT (
                         ID SERIAL PRIMARY KEY,
                         EMRI VARCHAR(100),
                         EMAIL VARCHAR(100),
                         BIRTHDATE DATE,
                         PHONE_NR VARCHAR(20),
                         PIKE INT,
                         KURSI_ID INT, CONSTRAINT FK_STUDENT_KURSI FOREIGN KEY (KURSI_ID) REFERENCES KURSI (ID));

SELECT * FROM STUDENT;

INSERT INTO STUDENT (EMRI, EMAIL, BIRTHDATE, PHONE_NR, PIKE, KURSI_ID) VALUES
('Anisa', 'anisa@gmail.com', '2000-05-10', '0691111111', 90, 1),
('Ardit', 'ardit@gmail.com', '1998-03-15', '0692222222', 85, 2),
('Blerina', 'blerina@gmail.com', '2002-07-20', '0693333333', 78, 4),
('Dren', 'dren@gmail.com', '1997-11-01', '0694444444', 88, 5),
('Era', 'era@gmail.com', '2001-01-25', '0695555555', 92, 6),
('Fjolla', 'fjolla@gmail.com', '1999-09-12', '0696666666', 80, 7),
('Gent', 'gent@gmail.com', '1995-12-30', '0697777777', 75, 8),
('Arta', 'arta@gmail.com', '2003-04-18', '0698888888', 95, 9),
('Ilir', 'ilir@gmail.com', '1996-06-09', '0699999999', 84, 10),
('Ariana', 'ariana@gmail.com', '2004-08-14', '0681234567', 89, 1);

ALTER TABLE STUDENT RENAME COLUMN PHONE_NR TO NR_TELEFONIT;

SELECT * FROM KURSI WHERE EMRI_KURSIT IS NOT NULL;

SELECT * FROM STUDENT WHERE EMRI LIKE 'A%';

SELECT * FROM KURSI WHERE CREATION_DATE BETWEEN '2023-01-01' AND '2025-12-31';

SELECT * FROM STUDENT WHERE BIRTHDATE <= CURRENT_DATE - INTERVAL '25 YEARS';

-- 1. Numeroni (funksioni count) sa kurse permbajne germen 'J' ne emer
SELECT COUNT(*) AS TOTAL_COUNT FROM KURSI WHERE EMRI_KURSIT LIKE '%J%';

-- 2. Nxirrni studentin qe ka maksimumin e pikeve.
SELECT EMRI, PIKE AS MAX_POINTS FROM STUDENT
WHERE PIKE = (SELECT MAX(PIKE) FROM STUDENT);

--OR FOR ALL STUDENTS
SELECT EMRI, PIKE FROM STUDENT ORDER BY PIKE DESC;

-- 3. Listoni kurset qe kane me shume se 3 studente
SELECT KURSI.EMRI_KURSIT, COUNT (STUDENT.ID) AS TOT_COUNT FROM KURSI
                                                                   INNER JOIN STUDENT ON KURSI.ID=STUDENT.KURSI_ID
GROUP BY KURSI.EMRI_KURSIT
HAVING COUNT(STUDENT.ID)>3;

-- 4. Shtoni nje tabele tjeter qe ta lidhni me foreign key te menaxhoni nje lidhje shume me shume midis 2 tabelave
CREATE TABLE STUDENT_KURSI(
                              STUDENT_ID INT,
                              KURSI_ID INT,
                              REGISTRATION_DT DATE,
                              PRIMARY KEY (STUDENT_ID, KURSI_ID),
                              FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
                              FOREIGN KEY (KURSI_ID) REFERENCES KURSI (ID));

-- 5. Listoni emer studenti dhe emer kursi per cdo student
SELECT KURSI.EMRI_KURSIT, STUDENT.EMRI FROM STUDENT_KURSI
                                                FULL JOIN STUDENT ON STUDENT_KURSI.STUDENT_ID = STUDENT.ID
                                                FULL JOIN KURSI ON STUDENT_KURSI.KURSI_ID = KURSI.ID;


ALTER TABLE STUDENT DROP CONSTRAINT FK_STUDENT_KURSI;
ALTER TABLE STUDENT DROP COLUMN KURSI_ID;
SELECT*FROM STUDENT;

-- DISTINCT
-- UNIQUE VALUES
SELECT DISTINCT KOHEZGJATJA FROM KURSI;
SELECT DISTINCT EMRI FROM STUDENT;
SELECT DISTINCT PROGRAMMING_LANGUAGE FROM KURSI;
SELECT DISTINCT EMRI, EMAIL FROM STUDENT;
-- COUNT THE VALUES
SELECT COUNT(DISTINCT KOHEZGJATJA) FROM KURSI;
-- ORDER THE UNIQES
SELECT DISTINCT EMRI, PIKE FROM STUDENT ORDER BY PIKE DESC;



SELECT * FROM STUDENT;
SELECT * FROM KURSI;

-- LIMIT AND OFFSET
-- SELECT ONLY THE FIRST 5 RECORDS FROM STUDENT; START FROM THE ID 4
SELECT * FROM STUDENT LIMIT 5;
SELECT * FROM STUDENT LIMIT 5 OFFSET 3;
-- 5 FIRST COURSES ORDERED BY NAME
SELECT * FROM KURSI ORDER BY EMRI_KURSIT
    LIMIT 5;
-- FROM 5TH ROW SKIP AND ORDER DESC BASED ON THE ID
SELECT ID, PROGRAMMING_LANGUAGE FROM KURSI
ORDER BY ID DESC
OFFSET 5;
-- SHOW FIRST 5 SKIPPING THE FIRST 2
SELECT EMRI_KURSIT, ID FROM KURSI LIMIT 5 OFFSET 2;
-- FOR ALL ID >= 5 SHOW THE FIRST 3
SELECT * FROM STUDENT WHERE ID >= 5 ORDER BY ID LIMIT 3;
